### ISSUE TITLE
"займання" вільних клітинок

### ISSUE THREAD

**Issue by g-old-en-eagle** [QuarantineGameTeam/team_5_game#20]
Після переходу на іншу клітинку, попередня лишається "зайнятою"

**Comment by grescher** [comment]
@g-old-en-eagle смотри, отслеживание клеток можно немного сократить. 
![tracks](https://i.ibb.co/SDk4Zj1/3.png)
На иллюстрации игрок остается на 25 клетке и каждый ход эта инфо дублируется.
Сделай пожалуйста так, чтобы если игрок остается на клетке, информация не дублировалась.
